<?php

use yii\db\Migration;
use yii\db\Schema;

class m160728_105954_redirect_mechanic extends Migration
{
    public function up()
    {
        $this->createTable('redirects', [
            'language'  =>  Schema::TYPE_CHAR."(5) NOT NULL DEFAULT 'ru-RU'",
            'source'    =>  Schema::TYPE_CHAR."(255) NOT NULL DEFAULT ''",
            'target'    =>  Schema::TYPE_CHAR."(255) NOT NULL DEFAULT ''",
        ]);

        $this->addPrimaryKey('lang_source', 'redirects', ['language', 'source']);

        $this->batchInsert('redirects', ['source', 'target', 'language'], [
            ['10x15', 'rukodelie/shemy-dlya-vyshivki', 'ru-RU'],
            ['12x15', 'rukodelie/shemy-dlya-vyshivki', 'ru-RU'],
            ['accessories', 'tehnika-dlya-krasoty/aksessuary', 'ru-RU'],
            ['aksessuary/kosmetichki/order-desc/visibility.core', 'aksessuary/kosmetichki', 'ru-RU'],
            ['banan', 'bizhuteriya/zakolki-dlya-volos/banan', 'ru-RU'],
            ['battery', 'vse-dlya-doma/torgovoe-oborudovanie/elementy-pitaniya', 'ru-RU'],
            ['bengalskiogni', 'prazdniki/novogodniy-tovar/bengalskie-ogni', 'ru-RU'],
            ['bigydi', 'krasota-i-zdorove/bigudi', 'ru-RU'],
            ['bigydi/order/date', 'krasota-i-zdorove/bigudi/order-date', 'ru-RU'],
            ['biser_melkiy_kitai', 'rukodelie/biser/biser-melkiy-kitay', 'ru-RU'],
            ['biser_rubka_kitai', 'rukodelie/biser/biser-rubka-kitay', 'ru-RU'],
            ['biser_rubka_kitai/asc', 'rukodelie/biser/biser-rubka-kitay', 'ru-RU'],
            ['biserkalibrovanuy', 'rukodelie/biser/biser-kalibrovaniy-kitay', 'ru-RU'],
            ['bizhuteriya/detskaya-bizhuteriya/detskie-braslety', 'bizhuteriya/detskaya-bizhuteriya', 'ru-RU'],
            ['bizhuteriya/pirsing/nabory-pirsinga', 'bizhuteriya/pirsing', 'ru-RU'],
            ['bizhuteriya/pirsing/page-9', 'bizhuteriya/pirsyng', 'ru-RU'],
            ['bizhuteriya/pirsing/pirsing-labret-gvozdiki', 'bizhuteriya/pirsing/labrety', 'ru-RU'],
            ['bizhuteriya/pirsing/tonneli-plagi-rastyazhki', 'bizhuteriya/pirsyng/tunneli-plagy-rostyazhky', 'uk-UA'],
            ['bizhuteriya/sergi/sergi-prestizh--gold-style', 'bizhuteriya/yuvelirna-bizhuteriya/serezhky-xuping-gold', 'uk-UA'],
            ['bizhuteriya/sergi/swarovski', 'bizhuteriya/yuvelirnaya-bizhuteriya/swarovski', 'ru-RU'],
            ['bizhuteriya/yuvelirnaya-bizhuteriya/cepochki', 'bizhuteriya/yuvelirnaya-bizhuteriya/cepochki-xuping', 'ru-RU'],
            ['bizhuteriya/zakolki-dlya-volos/utochki/order-asc/visibility.core', 'bizhuteriya/zakolki-dlya-volos/utochki', 'ru-RU'],
            ['braslet_cirkoniy', 'bizhuteriya/braslety/braslety-s-cirkoniem', 'ru-RU'],
            ['brasletnoga', 'bizhuteriya/braslety/braslet-na-nogu', 'ru-RU'],
            ['braslety', 'bizhuteriya/braslety', 'ru-RU'],
            ['brasletydetskie', 'rukodelie/detskoe/detskie-braslety', 'ru-RU'],
            ['brelok', 'aksessuary/brelok', 'ru-RU'],
            ['brelok/opt', 'aksessuary/brelok', 'ru-RU'],
            ['brelokaavto', 'aksessuary/brelok/brelok-avto', 'ru-RU'],
            ['broshki', 'bizhuteriya/broshki', 'ru-RU'],
            ['bublik', 'bizhuteriya/rezinki/bublik-dlya-volos', 'ru-RU'],
            ['busi_derevo', 'aksessuary/ukrainskiy-stil/ukrainskaya-bizhuteriya', 'ru-RU'],
            ['businy_metallik', 'rukodelie/businy/businy-metallicheskie', 'ru-RU'],
            ['businy_plastik', 'rukodelie/businy/businy-plastikovye', 'ru-RU'],
            ['businy_shambala', 'rukodelie/businy/businy-shambala', 'ru-RU'],
            ['businy_steklo', 'rukodelie/businy/businy-steklyannye', 'ru-RU'],
            ['businyshambala', 'rukodelie/businy/businy-shambala', 'ru-RU'],
            ['cepochka', 'bizhuteriya/cepochki', 'ru-RU'],
            ['chehli_dlya_ochkov', 'aksessuary/ochki/chehly-dlya-ochkov', 'ru-RU'],
            ['chehol', 'aksessuary/chehly-dlya-mobilnyh', 'ru-RU'],
            ['clock', 'aksessuary/chasy', 'ru-RU'],
            ['cvety', 'bizhuteriya/zakolki-dlya-volos/cvety', 'ru-RU'],
            ['dekor', 'rukodelie/dekor', 'ru-RU'],
            ['detckay', 'bizhuteriya/detskaya-bizhuteriya', 'ru-RU'],
            ['detskie_povyazki', 'bizhuteriya/detskaya-bizhuteriya/detskie-povyazki', 'ru-RU'],
            ['detskie/odruch', 'bizhuteriya/detskaya-bizhuteriya/detskie-obruchi', 'ru-RU'],
            ['detskiy-mir/kukly', 'tovary-dlya-detey/igrushki/kukly', 'ru-RU'],
            ['detskiy-mir/monster-high', 'tovary-dlya-detey/igrushki/kukly/monster-high', 'ru-RU'],
            ['dlya_britya', 'krasota-i-zdorove/dlya-britya', 'ru-RU'],
            ['dlya_kuhni', 'vse-dlya-doma/dlya-kuhni', 'ru-RU'],
            ['dorogiesergi', 'bizhuteriya/sergi', 'ru-RU'],
            ['dostavka', 'o-nas', 'ru-RU'],
            ['dtvistera', 'bizhuteriya/tvistery', 'ru-RU'],
            ['flower_head', 'rukodelie/golovki-cvetov', 'ru-RU'],
            ['furnitura', 'rukodelie/furnitura-dlya-rukodeliya', 'ru-RU'],
            ['furnitura/asc', 'rukodelie/furnitura-dlya-bizhuterii', 'ru-RU'],
            ['glasses', 'aksessuary/ochki', 'ru-RU'],
            ['glitter', 'rukodelie/blestki', 'ru-RU'],
            ['golovnoyubor', 'aksessuary/golovnye-ubory', 'ru-RU'],
            ['golovnuyeraznuye', 'aksessuary/golovnye-ubory', 'ru-RU'],
            ['grebishki', 'bizhuteriya/zakolki-dlya-volos/grebeshki', 'ru-RU'],
            ['grebni', 'bizhuteriya/zakolki-dlya-volos/grebeshki', 'ru-RU'],
            ['gvojdig', 'bizhuteriya/sergi/sergi-gvozdiki', 'ru-RU'],
            ['helper', 'pomoshch', 'ru-RU'],
            ['hlapa', 'prazdniki/novogodniy-tovar/karnavalnye-shlyapy', 'ru-RU'],
            ['hlopalka', 'bizhuteriya/zakolki-dlya-volos/hlopalka', 'ru-RU'],
            ['household-chemicals', 'vse-dlya-doma/torgovoe-oborudovanie/bytovaya-himiya', 'ru-RU'],
            ['igrushkaelka', 'prazdniki/novogodniy-tovar/igrushki-na-elku', 'ru-RU'],
            ['igrushkaelkaploska', 'prazdniki/novogodniy-tovar/igrushki-na-elku/ploskie', 'ru-RU'],
            ['igrushkasvet', 'prazdniki/novogodniy-tovar/igrushka-svetyashchayasya', 'ru-RU'],
            ['Index/palochki', 'bizhuteriya/zakolki-dlya-volos/kitayskie-palochki', 'ru-RU'],
            ['jewerly', 'vse-dlya-doma/torgovoe-oborudovanie/yuvelirnye-izdeliya', 'ru-RU'],
            ['kartinadlyavishivku', 'rukodelie/shemy-dlya-vyshivki', 'ru-RU'],
            ['kastrylya', 'vse-dlya-doma/dlya-kuhni/kastryuli', 'ru-RU'],
            ['kiev/biserrubka', 'rukodelie/biser/biser-rubka-kitay', 'ru-RU'],
            ['klatch', 'aksessuary/klatchi', 'ru-RU'],
            ['kluchku', 'vse-dlya-doma/torgovoe-oborudovanie/kryuchki-na-ekonompanel', 'ru-RU'],
            ['kolca', 'bizhuteriya/kolca', 'ru-RU'],
            ['kolcadeckie', 'bizhuteriya/detskaya-bizhuteriya/detskie-kolca', 'ru-RU'],
            ['kolie', 'bizhuteriya/kole', 'ru-RU'],
            ['konstruktor', 'tovary-dlya-detey/igrushki/konstruktor', 'ru-RU'],
            ['korobka', 'rukodelie/organayzery-dlya-furnitury', 'ru-RU'],
            ['krabiki_plastik', 'bizhuteriya/zakolki-dlya-volos/krabiki-plastik', 'ru-RU'],
            ['krabiki', 'bizhuteriya/zakolki-dlya-volos/krabiki-metall', 'ru-RU'],
            ['krabikmetal', 'bizhuteriya/zakolki-dlya-volos/krabiki-metall', 'ru-RU'],
            ['krabiku', 'bizhuteriya/zakolki-dlya-volos/krabiki-plastik', 'ru-RU'],
            ['kuhonnayaposuda', 'vse-dlya-doma/dlya-kuhni', 'ru-RU'],
            ['kuklamonsterhigh', 'tovary-dlya-detey/igrushki/kukly/monster-high', 'ru-RU'],
            ['legs', 'aksessuary/kolgotki-leginsy/legs', 'ru-RU'],
            ['lenta_atlas', 'rukodelie/lenty/lenta-atlasnaya', 'ru-RU'],
            ['lenta_bant', 'rukodelie/lenty/lenta-dlya-bantov', 'ru-RU'],
            ['lenta_bumaga', 'rukodelie/lenty/lenta-bumazhnaya', 'ru-RU'],
            ['lenta_florist', 'rukodelie/lenty/lenta-floristicheskaya', 'ru-RU'],
            ['lenta_repsovaya', 'rukodelie/lenty/lenta-repsovaya', 'ru-RU'],
            ['lopatka', 'krasota-i-zdorove/lopatki', 'ru-RU'],
            ['manikur_nabor', 'krasota-i-zdorove/manikyurnye-nabory', 'uk-UA'],
            ['manikurnozhnicu', 'krasota-i-zdorove/nozhnicy-manikyurnye', 'ru-RU'],
            ['monsterhigh', 'tovary-dlya-detey/igrushki/kukly/monster-high', 'ru-RU'],
            ['montera', 'bizhuteriya/zakolki-dlya-volos/montera', 'ru-RU'],
            ['mouline', 'rukodelie/vse-dlya-vyshivki-i-shitya/muline', 'ru-RU'],
            ['mouline', 'rukodillya/vse-dlya-vyshyvannya-ta-shyttya/muline', 'uk-UA'],
            ['nabor_dlya_rukodelia', 'rukodelie/biser/nabory-dlya-rukodeliya', 'ru-RU'],
            ['naborupodvesku/poddveskidlin', 'bizhuteriya/podveski/nabory', 'ru-RU'],
            ['naturalkam', 'rukodelie/businy/businy-nat-kamen', 'ru-RU'],
            ['nevedemka', 'bizhuteriya/zakolki-dlya-volos/nevidimka', 'ru-RU'],
            ['nitka_biser', 'rukodelie/vse-dlya-vyshivki-i-shitya/nit-bisernaya', 'ru-RU'],
            ['nitka_shveinaya', 'rukodelie/vse-dlya-vyshivki-i-shitya/nitka-shveynaya', 'ru-RU'],
            ['novoe-na-sayte/torgovoe-oborudovanie', 'vse-dlya-doma/torgovoe-oborudovanie', 'ru-RU'],
            ['novoe-na-sayte/torgovoe-oborudovanie/yuvelirnye-izdeliya', 'vse-dlya-doma/torgovoe-oborudovanie/yuvelirnye-izdeliya', 'ru-RU'],
            ['novogodniy-tovar/bengalskie-ogni', 'prazdniki/novogodniy-tovar/bengalskie-ogni', 'ru-RU'],
            ['novogodniy-tovar/igrushka-svetyaschayasya', 'svyata/novorichnyy-tovar/igrashka-shcho-svitytsya', 'uk-UA'],
            ['novogodniy-tovar/igrushka-svetyaschayasya', 'prazdniki/novogodniy-tovar/igrushka-svetyashchayasya', 'ru-RU'],
            ['novogodniy-tovar/igrushki-na-elku', 'prazdniki/novogodniy-tovar/igrushki-na-elku', 'ru-RU'],
            ['novogodniy-tovar/karnavalnye-shlyapy', 'prazdniki/novogodniy-tovar/karnavalnye-shlyapy', 'ru-RU'],
            ['novogodniy-tovar/krylya', 'prazdniki/novogodniy-tovar/krylya', 'ru-RU'],
            ['novogodniy-tovar/maski', 'prazdniki/novogodniy-tovar/maski', 'ru-RU'],
            ['novogodniy-tovar/novogodnie-kartiny', 'svyata/novorichnyy-tovar/novorichni-kartyny', 'uk-UA'],
            ['novogodniy-tovar/novogodniy-dozhdik', 'svyata/novorichnyy-tovar/novogodnyy-dozhdyk', 'uk-UA'],
            ['novogodniy-tovar/novogodniy-dozhdik', 'prazdniki/novogodniy-tovar/novogodniy-dozhdik', 'ru-RU'],
            ['novoktovar/elku', 'prazdniki/novogodniy-tovar/elka', 'ru-RU'],
            ['oborudovanie_bijuteriya', 'bizhuteriya/oborudovanie-dlya-bizhuterii', 'ru-RU'],
            ['ochki/order/asc', 'aksessuary/ochki', 'ru-RU'],
            ['office', 'vse-dlya-doma/torgovoe-oborudovanie/kancelyariya', 'ru-RU'],
            ['oplata', 'o-nas', 'ru-RU'],
            ['opt', 'o-nas', 'ru-RU'],
            ['osheiniki', 'vse-dlya-doma/tovary-dlya-zhivotnyh/biologicheskie-osheyniki', 'ru-RU'],
            ['otzyvy', 'o-nas', 'ru-RU'],
            ['paketupakovochniy', 'vse-dlya-doma/upakovochnye-pakety', 'ru-RU'],
            ['parovarka', 'vse-dlya-doma/dlya-kuhni/tehnika-dlya-kuhni', 'ru-RU'],
            ['payetki', 'rukodelie/payetki', 'ru-RU'],
            ['paymessage', 'o-nas', 'ru-RU'],
            ['piercing', 'bizhuteriya/pirsing', 'ru-RU'],
            ['pincet', 'krasota-i-zdorove/pincety', 'ru-RU'],
            ['plastik', 'bizhuteriya/sergi/sergi-plastik', 'ru-RU'],
            ['podarochnimichku', 'prazdniki/podarochnaya-upakovka', 'ru-RU'],
            ['poddveskidlin', 'bizhuteriya/podveski/podveski-dlinnye', 'ru-RU'],
            ['podveska/asc', 'bizhuteriya/podveski/order-asc', 'ru-RU'],
            ['poslugy/torgove-obladnannya/aksesuary-dlya-telefoniv', 'vse-dlya-domu/torgove-obladnannya/aksesuary-dlya-telefoniv', 'uk-UA'],
            ['poslugy/torgove-obladnannya/dlya-bizhuteriyi', 'vse-dlya-domu/torgove-obladnannya/dlya-bizhuteriyi', 'uk-UA'],
            ['poslugy/torgove-obladnannya/kvity', 'vse-dlya-domu/torgove-obladnannya/kvity', 'uk-UA'],
            ['poslugy/torgove-obladnannya/pobutova-himiya', 'vse-dlya-domu/torgove-obladnannya', 'uk-UA'],
            ['poslugy/torgove-obladnannya/vypichka', 'vse-dlya-domu/torgove-obladnannya/vypichka', 'uk-UA'],
            ['povyzki', 'bizhuteriya/povyazki', 'ru-RU'],
            ['pricheshka', 'bizhuteriya/zakolki-dlya-volos/stilnaya-pricheska', 'ru-RU'],
            ['products', 'vse-dlya-doma/torgovoe-oborudovanie/produkty', 'ru-RU'],
            ['pyalca', 'rukodelie/pyalca', 'ru-RU'],
            ['radiopriemnik', 'vse-dlya-doma/radiopriemniki-usb', 'ru-RU'],
            ['raznoe', 'vse-dlya-doma/raznoe', 'ru-RU'],
            ['raznoe/dlya-avtomobilya', 'vse-dlya-doma/avtovideoregistratory', 'ru-RU'],
            ['raznoe/dlya-kuhni', 'vse-dlya-doma/dlya-kuhni', 'ru-RU'],
            ['raznoe/dlya-kuhni/kastryuli', 'vse-dlya-doma/dlya-kuhni/kastryuli', 'ru-RU'],
            ['raznoe/dlya-kuhni/skovorodki---soteyniki', 'vse-dlya-doma/dlya-kuhni/skovorodki-soteyniki', 'ru-RU'],
            ['raznoe/dlya-kuhni/skovorodki-soteyniki', 'vse-dlya-doma/dlya-kuhni/skovorodki-soteyniki', 'ru-RU'],
            ['raznoe/elementy-pitaniya', 'vse-dlya-doma/elementy-pitaniya', 'ru-RU'],
            ['raznoe/fonarik', 'vse-dlya-doma/fonarik', 'ru-RU'],
            ['raznoe/izdeliya-iz-dereva', 'vse-dlya-doma/izdeliya-iz-dereva', 'ru-RU'],
            ['raznoe/kartiny', 'vse-dlya-domu/kartyny', 'uk-UA'],
            ['raznoe/kartiny', 'vse-dlya-doma/kartiny', 'ru-RU'],
            ['raznoe/podushki-dekorativnye', 'vse-dlya-doma/podushki-dekorativnye', 'ru-RU'],
            ['raznoe/raznoe', 'vse-dlya-doma/raznoe', 'ru-RU'],
            ['raznoe/tovary-dlya-zhivotnyh', 'vse-dlya-doma/tovary-dlya-zhivotnyh', 'ru-RU'],
            ['raznoe/tovary-dlya-zhivotnyh/igrushki-dlya-zhivotnyh', 'vse-dlya-doma/tovary-dlya-zhivotnyh/igrushki-dlya-zhivotnyh', 'ru-RU'],
            ['raznoe/upakovka/paket-upakovochniy', 'vse-dlya-doma/upakovochnye-pakety', 'ru-RU'],
            ['raznoe/upakovka/podarochnye-meshochki', 'vse-dlya-doma/upakovochnye-pakety', 'ru-RU'],
            ['returnsandexchanges', 'o-nas', 'ru-RU'],
            ['reviews', 'o-nas', 'ru-RU'],
            ['rezcu', 'krasota-i-zdorove/rezcy', 'ru-RU'],
            ['rezcu/order/asc', 'krasota-i-zdorove/rezcy/order-asc', 'ru-RU'],
            ['rezinka_silikon', 'bizhuteriya/rezinki/rezinki-silikonovye', 'ru-RU'],
            ['rezinkakamen', 'bizhuteriya/rezinki/rezinki-s-kamnyami', 'ru-RU'],
            ['rezunka', 'bizhuteriya/rezinki', 'ru-RU'],
            ['rezunka_kalush', 'bizhuteriya/rezinki/rezinki-kalush', 'ru-RU'],
            ['rezunka/order/date', 'bizhuteriya/rezinki/order-date', 'ru-RU'],
            ['ruchka', 'aksessuary/ruchki', 'ru-RU'],
            ['rukodelie/biser/biser-preciosa-chehiya', 'rukodillya/biser/biser-preciosa-250-gram', 'uk-UA'],
            ['rukodelie/biser/order-asc/visibility.core', 'rukodelie/biser/order-asc', 'ru-RU'],
            ['rukodelie/businy/order-asc/visibility.core', 'rukodelie/businy/order-asc', 'ru-RU'],
            ['rukodelie/furnitura-dlya-bizhuterii/zamki,-zastezhki', 'rukodelie/furnitura-dlya-bizhuterii/zamki-zastezhki', 'ru-RU'],
            ['rukodelie/nabory-dlya-biseropleteniya', 'rukodelie/biser/nabory-dlya-biseropleteniya', 'ru-RU'],
            ['rukodelie/nabory-dlya-rukodeliya', 'rukodelie/biser/nabory-dlya-rukodeliya', 'ru-RU'],
            ['rukodelie/ploskie-businy', 'rukodelie/businy/ploskie-businy', 'ru-RU'],
            ['rukodelie/ploskie-businy', 'rukodillya/namystyny/plaski-namystyny', 'uk-UA'],
            ['rukodelie/provolka', 'rukodelie/provoloka', 'ru-RU'],
            ['rukodelie/shemy-dlya-vyshivki/pasha', 'rukodillya/shemy-dlya-vyshyvannya/religiya/velykden', 'uk-UA'],
            ['rukodelie/vse-dlya-vyshivki-i-shitya/muline-dmc-franciya', 'rukodelie/vse-dlya-vyshivki-i-shitya/muline', 'ru-RU'],
            ['rukodillya/shemy-dlya-vyshyvannya/shema-12-h-15-sm', 'rukodillya/shemy-dlya-vyshyvannya', 'uk-UA'],
            ['rusachki', 'krasota-i-zdorove/kusachki', 'ru-RU'],
            ['salfetki', 'vse-dlya-doma/salfetki-dekorativnye', 'ru-RU'],
            ['salonam-krasoty/aksessuary', 'tehnika-dlya-krasoty/aksessuary', 'ru-RU'],
            ['salonam-krasoty/dlya-britya', 'krasa-i-zdorov039ya/dlya-golinnya', 'uk-UA'],
            ['salonam-krasoty/dlya-britya', 'krasota-i-zdorove/dlya-britya', 'ru-RU'],
            ['salonam-krasoty/kosmetika', 'krasota-i-zdorove/kosmetika', 'ru-RU'],
            ['salonam-krasoty/kusachki', 'krasota-i-zdorove/kusachki', 'ru-RU'],
            ['salonam-krasoty/lopatki', 'krasota-i-zdorove/lopatki', 'ru-RU'],
            ['salonam-krasoty/manikyurnye-nabory', 'krasota-i-zdorove/manikyurnye-nabory', 'ru-RU'],
            ['salonam-krasoty/nozhnicy', 'krasota-i-zdorove/nozhnicy-manikyurnye', 'uk-UA'],
            ['salonam-krasoty/nozhnicy-manikyurnye', 'krasota-i-zdorove/nozhnicy-manikyurnye', 'ru-RU'],
            ['salonam-krasoty/parfyumy', 'krasota-i-zdorove/parfyumy', 'ru-RU'],
            ['salonam-krasoty/pincety', 'krasota-i-zdorove/pincety', 'ru-RU'],
            ['salonam-krasoty/rascheski', 'krasa-i-zdorov039ya/grebinci', 'uk-UA'],
            ['salonam-krasoty/rascheski', 'krasota-i-zdorove/rascheski', 'ru-RU'],
            ['salonam-krasoty/resnicy', 'krasota-i-zdorove/resnicy', 'ru-RU'],
            ['salonam-krasoty/tehnika-dlya-salonov/-aksessuary-i-zapchasti-k-mashinkam-dlya-strizhki', 'tehnika-dlya-krasy/aksesuary-i-zapchastyny-do-mashynok-dlya-stryzhky', 'uk-UA'],
            ['salonam-krasoty/tehnika-dlya-salonov/-aksessuary-i-zapchasti-k-mashinkam-dlya-strizhki', 'tehnika-dlya-krasoty/aksessuary-i-zapchasti-k-mashinkam-dlya-strizhki', 'ru-RU'],
            ['salonam-krasoty/tehnika-dlya-salonov/feny', 'tehnika-dlya-krasoty/feny', 'ru-RU'],
            ['salonam-krasoty/tehnika-dlya-salonov/frezery-dlya-manikyura', 'tehnika-dlya-krasoty/frezery-dlya-manikyura', 'ru-RU'],
            ['salonam-krasoty/tehnika-dlya-salonov/mashinka-dlya-strizhki', 'tehnika-dlya-krasoty/mashinka-dlya-strizhki', 'ru-RU'],
            ['salonam-krasoty/tehnika-dlya-salonov/ployka', 'tehnika-dlya-krasoty/ployka', 'ru-RU'],
            ['salonam-krasoty/tehnika-dlya-salonov/voskoplavy', 'tehnika-dlya-krasoty/voskoplavy', 'ru-RU'],
            ['salonam-krasoty/tehnika-dlya-salonov/vytyazhka-manikyurnaya', 'tehnika-dlya-krasoty/vytyazhka-manikyurnaya', 'ru-RU'],
            ['salonam-krasoty/uhod-za-nozhkami', 'krasota-i-zdorove/uhod-za-nozhkami', 'ru-RU'],
            ['salonam-krasoty/uhod-za-volosami', 'krasota-i-zdorove/uhod-za-volosami', 'ru-RU'],
            ['salonam-krasoty/uhod-za-volosami-', 'krasota-i-zdorove/uhod-za-volosami', 'ru-RU'],
            ['sergi/sergiklipsu', 'bizhuteriya/sergi/sergi-klipsy', 'ru-RU'],
            ['sergiemal', 'bizhuteriya/sergi/cergi-emal', 'ru-RU'],
            ['sergiperi', 'bizhuteriya/sergi/sergi-perya', 'ru-RU'],
            ['sergipristij', 'bizhuteriya/yuvelirnaya-bizhuteriya/nabory-xuping', 'ru-RU'],
            ['setka', 'bizhuteriya/setki-dlya-volos', 'ru-RU'],
            ['shambala', 'bizhuteriya/braslety/braslety-shambala', 'ru-RU'],
            ['shambalapodveska', 'bizhuteriya/podveski/podveski-shambala', 'ru-RU'],
            ['shapkawoman', 'aksessuary/golovnye-ubory/shapki-zhenskie', 'ru-RU'],
            ['shemy_dlya_vyshyvki_cveti', 'rukodelie/shemy-dlya-vyshivki/cvety', 'ru-RU'],
            ['shemy_dlya_vyshyvki_pasha', 'rukodelie/shemy-dlya-vyshivki/religiya/pasha', 'ru-RU'],
            ['shlapavyal', 'aksessuary/golovnye-ubory/shlyapki', 'ru-RU'],
            ['shpilki', 'bizhuteriya/shpilki', 'ru-RU'],
            ['shpilku', 'bizhuteriya/shpilki', 'ru-RU'],
            ['silikon', 'bizhuteriya/rezinki/rezinki-silikonovye', 'ru-RU'],
            ['skovorodka', 'vse-dlya-doma/dlya-kuhni/skovorodki-soteyniki', 'ru-RU'],
            ['socseti', 'o-nas', 'ru-RU'],
            ['sotrudnichestvo', 'o-nas', 'ru-RU'],
            ['sponzhik', 'krasota-i-zdorove/sponzhiki', 'ru-RU'],
            ['status-zakaza', 'o-nas', 'ru-RU'],
            ['subscribe', 'o-nas', 'ru-RU'],
            ['swarovski', 'bizhuteriya/yuvelirnaya-bizhuteriya/swarovski', 'ru-RU'],
            ['tovary_dlya_gyvotnyh', 'vse-dlya-doma/tovary-dlya-zhivotnyh', 'ru-RU'],
            ['tovary-dlya-zhivotnyh', 'vse-dlya-doma/tovary-dlya-zhivotnyh', 'ru-RU'],
            ['trading-equipment', 'vse-dlya-doma/torgovoe-oborudovanie', 'ru-RU'],
            ['ukraine_eggs', 'aksessuary/ukrainskiy-stil/pashalnye-yayca', 'ru-RU'],
            ['ukraine_style/desc', 'aksessuary/ukrainskiy-stil/order-desc', 'ru-RU'],
            ['ukraine_symbols', 'aksessuary/ukrainskiy-stil/ukrainskaya-simvolika', 'ru-RU'],
            ['ukraine_syvenir', 'aksessuary/ukrainskiy-stil/ukrainskiy-suvenir', 'ru-RU'],
            ['uslugi/torgovoe-oborudovanie/dlya-bizhuterii', 'vse-dlya-doma/torgovoe-oborudovanie/dlya-bizhuterii', 'ru-RU'],
            ['uslugi/torgovoe-oborudovanie/elementy-pitaniya', 'vse-dlya-doma/torgovoe-oborudovanie/elementy-pitaniya', 'ru-RU'],
            ['uslugi/torgovoe-oborudovanie/vitriny', 'vse-dlya-doma/torgovoe-oborudovanie/vitriny', 'ru-RU'],
            ['uslugi/torgovoe-oborudovanie/vypechka', 'vse-dlya-doma/torgovoe-oborudovanie/vypechka', 'ru-RU'],
            ['utochkii', 'bizhuteriya/zakolki-dlya-volos/utochki', 'ru-RU'],
            ['vakansii', 'o-nas', 'ru-RU'],
            ['vkrutka', 'bizhuteriya/shpilki/vkrutka-pruzhinka', 'ru-RU'],
            ['vyazanie', 'rukodelie/vse-dlya-vyazaniya', 'ru-RU'],
            ['zakolkaavtomat', 'bizhuteriya/zakolki-dlya-volos/zakolka-avtomat', 'ru-RU'],
            ['zakolki', 'bizhuteriya/zakolki-dlya-volos', 'ru-RU'],
            ['zakolkicholka', 'bizhuteriya/zakolki-dlya-volos/zakolki-chelki', 'ru-RU'],
            ['zont', 'aksessuary/zonty', 'ru-RU'],
        ]);

    }

    public function down()
    {
        $this->dropTable('redirects');
        echo "m160728_105954_redirect_mechanic was successfully reverted.\n";
        return true;
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
