<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "banners".
 *
 * @property integer $ID
 * @property integer $category
 * @property integer $type
 * @property string $added
 * @property integer $order
 * @property string $dateFrom
 * @property string $dateTo
 * @property integer $deleted
 *
 * @property BannersTranslations $iD
 */
class Banner extends \yii\db\ActiveRecord
{

    const TYPE_IMAGE = 1;
    const TYPE_HTML = 2;
    const TYPE_GOOD = 3;
    const TYPE_GOOD_IMAGE = 4;

    public static function find(){
        return parent::find()->with('translations');
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'banners';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['category', 'added'], 'required'],
            [['category', 'type', 'order', 'deleted'], 'integer'],
            [['added', 'dateFrom', 'dateTo'], 'safe'],
            [['ID'], 'exist', 'skipOnError' => true, 'targetClass' => BannerTranslation::className(), 'targetAttribute' => ['ID' => 'ID']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => 'ID',
            'category' => 'Category',
            'type' => 'Type',
            'added' => 'Added',
            'order' => 'Order',
            'dateFrom' => 'Date From',
            'dateTo' => 'Date To',
            'deleted' => 'Deleted',
        ];
    }

    public function beforeSave($insert)
    {
        if($this->isNewRecord){
            $this->added = date('Y-m-d H:i:s');
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBanner()
    {
        return $this->getTranslationByKey(\Yii::$app->language);
    }

    public function getTranslations(){
        return $this->hasMany(BannerTranslation::className(), ['ID' => 'ID']);
    }

    /**
     * @param $key string
     * @return BannerTranslation()
     */
    public function getTranslationByKey($key){
        $defaultLang = 'ru-RU';
        $defaultTranslation = $needleTranslation = new BannerTranslation();

        foreach($this->translations as $translation){
            if($translation->language == $defaultLang){
                $defaultTranslation = $translation;
            }

            if($translation->language == $key){
                $needleTranslation = $translation;
            }
        }


        foreach($needleTranslation as $key => $value){
            if(empty($needleTranslation->$key) && !empty($defaultTranslation->$key)){
                $needleTranslation->$key = $defaultTranslation->$key;
            }
        }

        return $needleTranslation;
    }
}
