<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "banners_translations".
 *
 * @property integer $ID
 * @property integer $state
 * @property string $value
 * @property string $link
 * @property string $language
 */
class BannerTranslation extends \yii\db\ActiveRecord
{

    const STATE_ENABLED = 1;
    const STATE_DISABLED = 0;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'banners_translations';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ID', 'language'], 'required'],
            [['ID', 'state'], 'integer'],
            [['value'], 'string'],
            [['link', 'language'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => 'ID',
            'state' => 'State',
            'value' => 'Value',
            'link' => 'Link',
            'language' => 'Language',
        ];
    }

    public function beforeSave($insert)
    {
        if($this->isNewRecord && empty($this->ID)){
            $this->ID = (self::find()->max('ID') + 1);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
