<?php
/**
 * Created by PhpStorm.
 * User: bobroid
 * Date: 27.04.16
 * Time: 17:40
 */

namespace common\models;


use common\helpers\TranslitHelper;
use yii\db\ActiveRecord;

/**
 * @property integer $sequence
 * @property string $phoneNumber
 * @property integer $enabled
 */
class CategoryTranslation extends ActiveRecord
{

    public static function tableName(){
        return 'category_translations';
    }

    public function rules(){
        return [
            [['language', 'Name', 'link', 'title'], 'string'],
            [['enabled', 'sequence'], 'integer']
        ];
    }

    public function getCategoryLink(){
        $category = $this->ID;
        if(filter_var($category, FILTER_VALIDATE_INT)){
            $c = Category::findOne(['ID' => $category]);
            $category = $c->Code;
        }

        $c = Category::getParentCategories($category);

        if(empty($c)){
            return false;
        }

        $links = [];

        foreach($c as $cc){
            $links[] = TranslitHelper::to($cc->Name);
        }

        return implode('/', $links);
    }

    public function beforeSave($insert)
    {
        if(empty($this->Name)){
            return false;
        }

        if(empty($this->language)){
            $this->language = \Yii::$app->language;
        }

        if($this->isNewRecord || $this->oldAttributes['Name'] != $this->Name || empty($this->link) || (!empty($this->categoryLink) && $this->link != ($this->categoryLink.'/'.TranslitHelper::to($this->Name)))){
            $this->link = $this->categoryLink.'/'.TranslitHelper::to($this->Name);
        }

        if(empty($this->link)){
            $this->link = '-';
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes){
        if(!empty(array_intersect(['Name', 'link'], array_keys($changedAttributes)))){
            $c = Category::findOne(['ID' => $this->ID]);
            foreach($c->childs as $cc){
                $cc->translation->save(false);
            }
        }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterFind(){
        $this->link = urldecode($this->link);

        return parent::afterFind();
    }

}