<?php
/**
 * Created by PhpStorm.
 * User: bobroid
 * Date: 27.04.16
 * Time: 17:40
 */

namespace common\models;


use common\helpers\TranslitHelper;
use yii\db\ActiveRecord;

/**
 * @property integer $sequence
 * @property string $phoneNumber
 * @property integer $enabled
 */
class CategoryTranslation extends ActiveRecord
{

    public static function tableName(){
        return 'category_translations';
    }

    public function rules(){
        return [
            [['language', 'Name', 'link', 'title'], 'string'],
            [['enabled', 'sequence'], 'integer']
        ];
    }

    public function beforeSave($insert)
    {
        if(empty($this->Name)){
            return false;
        }

        if(empty($this->language)){
            $this->language = \Yii::$app->language;
        }

        if($this->isNewRecord || $this->oldAttributes['Name'] != $this->Name || empty($this->link)){
            $this->link = TranslitHelper::to($this->Name);
        }

        if(empty($this->link)){
            $this->link = '-';
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterFind(){
        $this->link = urldecode($this->link);

        return parent::afterFind();
    }

}