<?php
/**
 * Created by PhpStorm.
 * User: bobroid
 * Date: 29.04.16
 * Time: 17:49
 */

namespace frontend\modules\account\models;


use yii\base\Model;

class ChangePasswordForm extends Model
{

    public $oldPassword;

    public $newPassword;

    public $newPassword_repeat;

    public function rules(){
        return [
            [['oldPassword', 'newPassword', 'newPassword_repeat'], 'required'],
            [['oldPassword', 'newPassword', 'newPassword_repeat'], 'string', 'min' => 6],
            ['oldPassword', 'validatePassword'],
            ['newPassword', 'compare', 'message' => 'Пароли должны совпадать!'],
        ];
    }

    public function validatePassword($attribute, $params){
        if(!empty($this->$attribute) && !\Yii::$app->user->identity->validatePassword($this->oldPassword)){
            $this->addError($attribute, \Yii::t('shop', 'Вы ввели неверный пароль!'));
        }
    }

    public function attributeLabels()
    {
        return [
            'oldPassword'   =>  \Yii::t('shop', 'Текущий пароль'),
            'newPassword'   =>  \Yii::t('shop', 'Новый пароль'),
            'newPassword_repeat'   =>  \Yii::t('shop', 'Новый пароль ещё раз'),
        ];
    }

    public function validate($attributeNames = null, $clearErrors = true)
    {


        return parent::validate($attributeNames, $clearErrors); // TODO: Change the autogenerated stub
    }

    public function changePassword(){
        if($this->validate()){

        }
    }

}