<?php
/**
 * Created by PhpStorm.
 * User: bobroid
 * Date: 28.06.16
 * Time: 17:21
 */

namespace backend\modules\charts\models;


use yii\base\Model;

/**
 * @property CashboxDayReport[] stats
 */
class CashboxMonthReport extends Model
{

    public $month = '';
    public $year = '';

    private $_orders = [];

    public function init()
    {
        $this->month = date('m');
        $this->year = date('Y');

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getOrders(){
        if(empty($this->_orders)){
            $dateFrom = strtotime($this->year.'-'.$this->month.'-01');

            $search = new HistorySearch([
                'dateFrom'  =>  $dateFrom,
                'dateTo'    =>  strtotime($this->year.'-'.$this->month.'-'.date('t', $dateFrom))
            ]);

            $search = $search->search(\Yii::$app->request->get());
            $this->_orders = $search->all();
        }

        return $this->_orders;
    }

    public function getStats(){
        $dayFormatted = $this->year.'-'.$this->month.'-01';

        $stats = [];

        $lastDay = date('t', strtotime($dayFormatted));

        for($day = 1; $day <= $lastDay && $day <= date('d'); $day++){
            $dayReport = new CashboxDayReport([
                'date'  =>  substr($dayFormatted, 0, -strlen($day)).$day
            ]);

            $stats[] = $dayReport;
        }

        return $stats;
    }

}