<?php
/**
 * Created by PhpStorm.
 * User: bobroid
 * Date: 07.07.16
 * Time: 20:26
 */

namespace backend\models;


class CashboxMoney extends \common\models\CashboxMoney
{

    public function beforeSave($insert)
    {
        if (empty($this->cashbox)){
            $this->cashbox = \Yii::$app->params['configuration']->defaultCashboxID;
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}