<?php
/**
 * Created by PhpStorm.
 * User: bobroid
 * Date: 03.03.16
 * Time: 17:36
 */

namespace backend\models;

use common\models\GoodsPhoto;
use yii\web\NotFoundHttpException;

class GoodPhoto extends GoodsPhoto
{
    public function behaviors()
    {
        return [
            'LoggableBehavior' => [
                'class' => 'sammaye\audittrail\LoggableBehavior',
                'options'   =>  [
                    'alternateKey'      =>  'itemid',
                    'discardSaveCreate' =>  true,
                    'field'             =>  'additionalPhoto',
                    'model'             =>  Good::className()
                ],
                'ignored' => [
                    'itemid',
                    'id',
                    ''
                ],
            ]
        ];
    }

    public function afterDelete()
    {
        /*
         * Автоматическое отключение товара при удалении последней фотографии
         */
        $photos = self::find()->where(['itemid' => $this->itemid])->count();

        if($photos <= 0){
            $good = Good::findOne($this->itemid);

            if($good){
                $good->show_img = 0;

                $good->save(false);
            }
        }

        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        if($this->isNewRecord && empty($this->order)){
            $this->order = self::find()->select('MAX(`order`)')->where(['itemid' => $this->itemid])->scalar() + 1;
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}