<?php
/**
 * Created by PhpStorm.
 * User: bobroid
 * Date: 03.03.16
 * Time: 17:36
 */

namespace backend\models;

use common\models\GoodsPhoto;

class GoodPhoto extends GoodsPhoto
{
    public function behaviors()
    {
        return [
            'LoggableBehavior' => [
                'class' => 'sammaye\audittrail\LoggableBehavior',
                'options'   =>  [
                    'alternateKey'      =>  'itemid',
                    'discardSaveCreate' =>  true,
                    'field'             =>  'additionalPhoto',
                    'model'             =>  Good::className()
                ],
                'ignored' => [
                    'itemid',
                    'id',
                    ''
                ],
            ]
        ];
    }

    public function beforeSave($insert)
    {
        if($this->isNewRecord){
            $this->order = self::find()->select('MAX(`order`)')->where(['itemid' => $this->itemid])->scalar() + 1;
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}