<?php
/**
 * Created by PhpStorm.
 * User: bobroid
 * Date: 09.06.16
 * Time: 17:16
 */

namespace backend\models;


/**
 * @property integer monthPlan
 */
class Shop extends \common\models\Shop
{

    public $month;

    public $year;

    public function init()
    {
        $this->month = date('m');
        $this->year = date('Y');

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getMonthPlan($month = null, $year = null)
    {
        if(empty($month)){
            $month = $this->month;
        }
        
        if(empty($year)){
            $year = $this->month;
        }

        return parent::getMonthPlan($month, $year); // TODO: Change the autogenerated stub
    }

}