<?php
/**
 * Created by PhpStorm.
 * User: bobroid
 * Date: 09.06.16
 * Time: 17:16
 */

namespace backend\models;
use common\models\Cashbox;


/**
 * @property integer monthPlan
 * @property mixed possibleCashboxes
 * @property mixed defaultCashbox
 */
class Shop extends \common\models\Shop
{

    public $month;

    public $year;

    public function init()
    {
        $this->month = date('m');
        $this->year = date('Y');

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getMonthPlan($month = null, $year = null)
    {
        if(empty($month)){
            $month = $this->month;
        }
        
        if(empty($year)){
            $year = $this->month;
        }

        return parent::getMonthPlan($month, $year); // TODO: Change the autogenerated stub
    }

    public function getPossibleCashboxes(){
        return $this->hasMany(Cashbox::className(), ['store' => 'id']);
    }

    public function getDefaultCashbox(){
        foreach($this->possibleCashboxes as $cashbox){
            if($cashbox->default == 1){
                return $cashbox;
            }
        }

        if(array_key_exists(0, $this->possibleCashboxes)){
            return $this->possibleCashboxes[0];
        }

        $defaultCashbox = new Cashbox([
            'store'     =>  $this->id,
            'default'   =>  1
        ]);

        $defaultCashbox->save(false);

        return $defaultCashbox;
    }

    public function getDefaultCashboxID(){
        return $this->defaultCashbox->ID;
    }

}