<?php

namespace frontend\models;

use Yii;

class Cart extends \common\models\Cart
{

    public function getItemsQuery(){
        return Good::find()
            ->where(['in', 'id',
                self::find()
                    ->select('itemID')
                    ->where(['cartCode' => \Yii::$app->cart->cartCode])]);
    }

    public function getItems(){
        return $this->getItemsQuery()->all();
    }

    public function beforeSave($insert)
    {
        $this->date = date('Y-m-d H:i:s');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
