<?php
/**
 * Created by PhpStorm.
 * User: bobroid
 * Date: 29.04.16
 * Time: 16:08
 */

namespace frontend\models;


class SborkaItem extends \common\models\SborkaItem
{


    public static function find(){
        return parent::find()->with('good');
    }

    public function setGood($good){
        $this->good = $good;
    }

    public function afterFind()
    {
        if(empty($this->good)){
            $this->good = new Good();
        }

        parent::afterFind(); // TODO: Change the autogenerated stub
    }

}