<?php

namespace backend\modules\charts\controllers;

use backend\controllers\SiteController as Controller;
use backend\models\History;
use backend\models\Shop;
use backend\modules\charts\models\HistorySearch;
use backend\modules\charts\models\MonthReport;

class DefaultController extends Controller
{
    
    public function beforeAction($action)
    {
        if($action->id != 'index'){
            $this->getView()->params['breadcrumbs'][] = [
                'url'   =>  '/charts',
                'label' =>  'Отчёты'
            ];
        }
        
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        if(\Yii::$app->request->post()){
            \Yii::$app->response->format = 'json';
            return \Yii::$app->request->post();
        }

        /*$p = null;
        if(\Yii::$app->request->get('minPeriod') || \Yii::$app->request->get('maxPeriod')){
            $p = [];

            if(\Yii::$app->request->get('minPeriod')){
                $p['min'] = \Yii::$app->request->get('minPeriod');
            }

            if(\Yii::$app->request->get('maxPeriod')){
                $p['max'] = \Yii::$app->request->get('maxPeriod');
            }

        }

        $q = History::getShopSiteOrdersCount($p);
        $a = History::getPaymentStats($p);*/

        return $this->render('stats', [
            'possibleReports'   =>  [
                [
                    'url'   =>  '/charts/shop',
                    'label' =>  'Продажи магазина'
                ],
            ]
        ]);
    }

    public function actionShop(){
        $shop = \Yii::$app->params['configuration'];

        $shop->month = 5;

        $report = new MonthReport();

        $report->shop = $shop;

        return $this->render('shop',
            [
                'shop'      =>  $shop,
                'report'    =>  $report
            ]
        );
    }

    public function actionGoods(){
        $mod = \Yii::$app->request->get("mod");
        $mod = empty($mod) ? '' : $mod;

        return $this->render('goods', [

        ]);
    }
}
